receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  zipkin:
    endpoint: ${ZIPKIN_URL}/api/v2/spans
    tls:
      insecure: true
#  jaeger:
#    endpoint: ${JAEGER_COLLECTOR_URL}
#    tls:
#      insecure: true
  prometheus:
    # /metrics
    endpoint: ${OTEL_COLLECTOR_EXPORTER_PROMETHEUS_ENDPOINT}
#  prometheusremotewrite:
#    endpoint: ${PROMETHEUS_URL}/api/v1/push
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - zipkin
#        - jaeger
    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - prometheus
#        - prometheusremotewrite
#    logs:
#      receivers:
#        - otlp
#      processors:
#        - batch
#      exporters:
#        - logging
