name: sd

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - ${ZIPKIN_PORT}:9411
    networks:
      - spring

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - ${JAEGER_PORT}:16686
      - ${JAEGER_COLLECTOR_PORT}:14250
    networks:
      - spring

  prometheus:
    image: prom/prometheus
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - ./config/prometheus-config.yml:/etc/prometheus/prometheus-config.yml
    command:
      - --config.file=/etc/prometheus/prometheus-config.yml
    networks:
      - spring

  elasticsearch:
    image: elasticsearch:${ELASTIC_STACK_TAG}
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - spring
    ports:
      - ${ELASTICSEARCH_PORT}:9200

  kibana:
    image: kibana:${ELASTIC_STACK_TAG}
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_URL}
    ports:
      - ${KIBANA_PORT}:5601
    networks:
      - spring
    depends_on:
      - elasticsearch

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    environment:
      - OTEL_COLLECTOR_EXPORTER_PROMETHEUS_ENDPOINT=${OTEL_COLLECTOR_EXPORTER_PROMETHEUS_ENDPOINT}
      - ZIPKIN_URL=${ZIPKIN_URL}
      - JAEGER_COLLECTOR_URL=${JAEGER_COLLECTOR_URL}
      - PROMETHEUS_URL=${PROMETHEUS_URL}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
    ports:
      - ${OTEL_COLLECTOR_RECEIVER_GRPC_PORT}:4317
      - ${OTEL_COLLECTOR_RECEIVER_HTTP_PORT}:4318
      - ${OTEL_COLLECTOR_EXPORTER_PROMETHEUS_PORT}:8889
    volumes:
      - ./config/otel-collector-config.yml:/etc/otel-collector-config.yml
    command:
      - --config=/etc/otel-collector-config.yml
    networks:
      - spring
    depends_on:
      - zipkin
#      - jaeger
      - prometheus
      - kibana

  discovery:
    image: alexengrig/discovery-service:${SERVICE_TAG}
    environment:
      - OTEL_SERVICE_NAME=discovery-service
    env_file:
      - otel.env
    ports:
      - ${DISCOVERY_PORT}:8761
    networks:
      - spring
    depends_on:
      - otel-collector

  producer:
    image: alexengrig/producer-service:${SERVICE_TAG}
    environment:
      - DISCOVERY_URL=${DISCOVERY_URL}
      - OTEL_SERVICE_NAME=producer-service
    env_file:
      - otel.env
    ports:
      - ${PRODUCER_PORT}:8082
    networks:
      - spring
    depends_on:
      - otel-collector
      - discovery

  consumer:
    image: alexengrig/consumer-service:${SERVICE_TAG}
    environment:
      - DISCOVERY_URL=${DISCOVERY_URL}
      - OTEL_SERVICE_NAME=consumer-service
    env_file:
      - otel.env
    ports:
      - ${CONSUMER_PORT}:8081
    networks:
      - spring
    depends_on:
      - otel-collector
      - discovery
      - producer

networks:
  spring:
    driver: bridge
