common:
  storage:
    backend: s3
    s3:
      endpoint: minio:9000
      access_key_id: mimir-access
      secret_access_key: mimir-secret
      bucket_name: mimir-bucket
      insecure: true

blocks_storage:
  s3:
    bucket_name: mimir-blocks
